### PR TITLE
use async_hooks

### PR DESCRIPTION
**Pull request by mafintosh**
Uses async_hooks to track the handles and stacks. Much, much cleaner but only supported by node >= 8 AFAIK (cc @andreas_madsen). 

Thoughts @ralphtheninja @yoshuawuyts ?

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@mafintosh I know that you usually want to have support for many node versions, but iirc there has been some problems with this module due to differences in node implementations. In this case, moving up to node 8 to make it work better and also cleaner code is a good trade off.

**Comment by ralphtheninja** [comment]
New major I guess :wink:

**Comment by yoshuawuyts** [comment]
@mafintosh cleaner, I like it

**Comment by mafintosh** [comment]
2.0.0

**Comment by fluxsauce** [comment]
This decision is not user friendly; the README doesn't state that Node 8 is required, there's no CHANGELOG or release notes, you don't have an `engines` in your `package.json` that would have highlighted the problem, and there's a lot of folks still on Node 6.

I get wanting to use the latest technologies. Please find a balance by updating documentation (state in the README the version requirements and what to do if you don't have it), enforcement (`package.json` `engines`), and using release notes to declare why it's a major version.

**Comment by mafintosh** [comment]
Feel free to send a PR :)

**Comment by fluxsauce** [comment]
Starred this three weeks ago, finally got around to it :-)

**Pull request merged**
