### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Pomax**
this does not need to be installed globally.

### CODE REVIEW

**Comment by adminy** [comment]
I find it particularly useful to use it this way:

**Comment by Pomax** [comment]
probably something you'll want to write your own PR for, so that @mafintosh can make decisions and leave comments on them separately.

**Comment by adminy** [comment]
Done in https://github.com/mafintosh/why-is-node-running/pull/63

**Comment by jonkoops** [comment]
Thanks for the PR. I've updated the installation options to reflect global installation as an optional choice under #74, so I will close this one.

**Comment by Pomax** [comment]
@jonkoops cheers. Small note: the use of short flags is pretty universal, so telling folks to use `-D` or `-g` is nicer than the rather verbose full name flags with extra dashes.

**Comment by jonkoops** [comment]
Thanks for the feedback, but I disagree. You never know the skill level of the person installing your packages, so it's best to assume that they don't know the meaning of any of these shorthands. Giving them the more verbose version adds extra clarity, and for those that already know the commands there isn't really that much contextual overhead. I'd rather be a bit more verbose here if that means it is inclusive.

**Pull request closed without merging**
